<div class="storefinder-default-header">
    <p class="store-finder-header">
        <i class="fas fa-map-pin"></i> <?php echo  __('Directions');?>
    </p>
</div>

<div class="storefinder-directions-body">
    <div  id="directions"  class="storefinder-directions-inner-wrapper" data-bind="scope:'directions'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>


<script type="text/x-magento-init">
                {
                    "*": {
                        "Magento_Ui/js/core/app": {
                           "components": {
                                "directions": {
                                    "component": "Peasoup_Storefinder/js/directions",
                                    "template" : "Peasoup_Storefinder/view/directions"
                                }
                            }
                        }
                    }
                }
</script>