<div class="storefinder-default-header">
    <p class="store-finder-header">
        <i class="far fa-question-circle"></i> <?php echo  __('Store Information');?>
    </p>
</div>
<div id="storefinder-information-table">
            <table>
                <tr>
                    <th>
                        <p><?php echo  __('Address');?></p>
                    </th>
                    <td>
                        <p><?php echo $this->getStore()->getData('address1')?></p>
                        <p><?php echo $this->getStore()->getData('address2')?></p>
                        <p><?php echo $this->getStore()->getTown()?></p>
                        <p><?php echo $this->getStore()->getCountry()?></p>
                    </td>
                </tr>
                <tr>
                    <th>
                        <p><?php echo  __('Postcode');?></p>
                    </th>
                    <td>
                        <p><?php echo $this->getStore()->getPostcode()?></p>
                    </td>
                </tr>
                <tr>
                    <th>
                        <p><?php echo  __('Telephone');?></p>
                    </th>
                    <td>
                        <p><?php echo $this->getStore()->getTelephone()?></p>
                    </td>
                </tr>
                <tr>
                    <th>
                        <p><?php echo  __('Email');?></p>
                    </th>
                    <td>
                        <p><?php echo $this->getStore()->getEmail()?></p>
                    </td>
                </tr>
            </table>
</div>