<?php if($this->getStore()->getNotes() !=""):?>
    <div class="alert alert-danger" role="alert">
        <?php echo  $this->getStore()->getNotes();?>
    </div>
<?php endif; ?>

<div class="store-finder-intro-header ">
    <div class="store-finder-header">
        <p>
            <i class="fa fa-15x fa-home" aria-hidden="true"></i>
            <?php echo  $this->getStore()->getName() ." Vape Shop";?>
        </p>
    </div>
</div>

<div class=" text-left wrapper-block" data-role="content">
    <div class="collapsible-content">

        <div class="store-finder-intro-body">
            <p>
                <?php echo $this->getStore()->getSynopsis();?>
            </p>
        </div>
    </div>
</div>