<div class="testimonials-wrapper">
    <div class="store-finder-intro-header ">
            <div class="col-sm-12 col-md-12 store-finder-header">
                <div class="col-sm-8 col-md-10">
                    <div class="row">
                        <p>
                            <i class="fa fa-15x fa-weixin" aria-hidden="true"></i>
                            <?php echo  __('What Other People Say About Us');?>
                        </p>
                    </div>
                </div>
                <div class="hidden-xs visible-sm visible-md visible-lg col-sm-4 col-md-2 pull-right ">
                    <div class="slick-theme">
                        <div>
                            <div class="slick-nav reviews-nav">
                                <div class="slick-next-item-reviews white-arrow">
                                    <img src="https://www.vapedirect.com/pub/media/wysiwyg/sliders/arrow-right-white.png">
                                </div>
                                <div class="slick-previous-item-reviews white-arrow">
                                    <img src="https://www.vapedirect.com/pub/media/wysiwyg/sliders/arrow-left-white.png">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>

        <div class="row">
            <div class="col-xs-12">
                <div class=" block-slider block-slider-default">
                    <div class="block-inner">
                        <ul class="slides owl-carousel owl-theme " id="ul-reviews">
                            <?php foreach($this->getTestimonials() as $testimonials):?>
                                <?php if ($itemBlock = $block->getChildBlock('testimonials.container')): ?>
                                    <?php echo $itemBlock->setTestimonial($testimonials)->getChildHtml(); ?>
                                <?php endif; ?>
                            <?php endforeach;?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script>
    require([
        'jquery',
        'slickcarousel',
        'textCollapseNew'
    ], function () {
        'use strict';
        jQuery.noConflict();
        var slider = jQuery("#ul-reviews");

        slider.on('init', function() {
            var newBlocks = jQuery('.list-group-item-inner');
            jQuery(newBlocks).each(function (index, value) {

                var id =  jQuery(this).attr('id');

                if(id==""){
                    return true;
                }

                jQuery('.text-collapse'+id).showHide({
                    speed: 500, // speed you want the toggle to happen
                    easing: '', // the animation effect you want. Remove this line if you dont want an effect and if you haven't included jQuery UI
                    changeText: 1, // if you dont want the button text to change, set this to 0
                    showText: 'Show Review <span class="fa fa-angle-double-down"></span>',// the button text to show when a div is closed
                    hideText: 'Hide Review <span class="fa fa-angle-double-up"></span>' // the button text to show when a div is open

                });

            });
       });



        jQuery( window ).load(function() {

            var newBlocks = jQuery('.list-group-item-inner');
            jQuery(newBlocks).each(function (index, value) {

                var id =  jQuery(this).attr('id');

                if(id=="" || id.length < 8){
                    return true;
                }

                jQuery(this).find('.img-circle').addClass('fa-spinner');
                console.log(id);
                jQuery.ajax({
                    url: "/socialfeed/ajax/user",
                    method: "POST",
                    data: { userID :  id },
                    dataType: "json",
                    async:true,
                    success: function(data){
                        if(data) {
                            var el = jQuery('#'+id).find('.panel-heading');
                            el.find('.fa-spinner').remove();
                            var img = jQuery('<img style="width:50%;margin-left:25%;height:125px;" class="img-circle img-thumbnail">');
                            img.attr('src', data);
                            img.appendTo(el);
                        }

                    }
                });

            });

        });


            slider.slick({
            dots: false,
            rows:1,
            lazyLoad: 'ondemand',
            infinite: false,
            prevArrow: jQuery('.slick-previous-item-reviews'),
            nextArrow: jQuery('.slick-next-item-reviews'),
            speed: 800,
            arrows: true,
            adaptiveHeight: true,
            slidesToShow: 4,
            slidesToScroll:4,
            responsive: [
                {
                    breakpoint: 1366,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll:3,
                        infinite: false,
                        dots: false
                    }
                },
                {
                    breakpoint: 800,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2
                    }
                },
                {
                    breakpoint: 480,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1
                    }
                }
                // You can unslick at a given breakpoint now by adding:
                // settings: "unslick"
                // instead of a settings object
            ]
        });



    });
</script>