<div id="storefinder" class="storefinder">

    <div id="storefinder-introduction" class="store-finder-margin">
        <?php echo $this->getChildHtml('storefinder.home.introduction');?>
    </div>

    <div id="storefinder-search" class="store-finder-margin">
        <?php echo $this->getChildHtml('storefinder.home.search');?>
    </div>

    <div id="storefinder-list">
            <?php echo $this->getChildHtml('storefinder.home.list');?>
    </div>

    <div id="storefinder-index-map">
        <?php echo $this->getChildHtml('storefinder.home.map');?>
    </div>

</div>
