<div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true}}'>
    <div class="col-xs-12" data-role="collapsible">
        <div class="text-center" data-role="collapsible">
            <div data-role="trigger">
                <div class="store-finder-intro-header ">
                    <div class="store-finder-header">
                        <p>
                            <i class="fa fa-15x fa-home" aria-hidden="true"></i> <?php echo  __('Find your Local Vape Direct Store')?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="" data-role="content">
        <div class="store-finder-intro-body">
            <p>
                <?php echo __('Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.')?>
            </p>
        </div>
    </div>
</div>


