<div id="storefinder" class="storefinder">

    <div id="storefinder-notification" class="store-finder-margin">
        <?php echo $this->getChildHtml('storefinder.view.notification');?>
    </div>

    <div id="storefinder-introduction" class="store-finder-margin">
        <?php echo $this->getChildHtml('storefinder.view.introduction');?>
    </div>

    <div id="storefinder-directions" class="store-finder-margin">
        <?php echo $this->getChildHtml('storefinder.view.directions');?>
    </div>

    <div id="storefinder-map" class="store-finder-margin">
        <?php echo $this->getChildHtml('storefinder.view.map');?>
    </div>

    <div id="storefinder-opening-hours" class="store-finder-margin">
        <?php echo $this->getChildHtml('storefinder.view.opening.hours');?>
    </div>

    <div id="storefinder-gallery" class="store-finder-margin">
        <?php echo $this->getChildHtml('storefinder.view.gallery');?>
    </div>

    <div id="storefinder-information" class="store-finder-margin">
        <?php echo $this->getChildHtml('storefinder.view.information');?>
    </div>



</div>

<script type="text/x-magento-init">
                {


                    "*" : {
                        "Peasoup_Storefinder/js/storesList" :
                                                              {
                                                                "id":"<?php echo $this->getStore()->getId();?>"
                                                              }
                    },
                       "[data-role=storefinder-googlemap]" : {
                                               "googleMap" :{
                                                 "id":"<?php echo $this->getStore()->getId();?>"
                                               }
                                               }
                }
</script>