<fieldset class="admin__fieldset" >
    <div class="admin__field">
        <div class="admin__field-label">
            <label>
                <span>Get co-ordinates from postcode</span>
            </label>
        </div>
        <div class="admin__field-control" >
            <button id="postcodeButton" title="Load Postcode Store" type="button" class="action- scalable primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"  data-ui-id="load-postcoce-button" role="button" aria-disabled="false">
                <span class="ui-button-text">
                <span>Load Marker</span>
            </span></button>
        </div>
    </div>
</fieldset>