
    <div class="store-finder-search-header">
        <p>
            <i class="fa fa-15x fa-search" aria-hidden="true"></i>
            <?php echo  __('Search by Distance')?>
        </p>
    </div>

    <div id="search" class="search-inner-wrap" >
            <div class="postcode-wrapper col-sm-4 col-md-4 col-lg-4" data-bind="scope:'search'">
                <input data-bind="textInput: postCode" type="text" name="postcodesearch" id="postcodeSearch" placeholder="Enter a location"/>
            </div>

            <div class="slider-wrapper smile-es-range-slider col-sm-3 col-md-4  col-lg-4" data-role="storefinder-distance-slider">
                <div data-role="slider-bar"></div>
            </div>

            <div class="buttons-wrapper col-sm-5 col-md-4  col-lg-3" data-bind="scope:'search'">
                <div class="miles-text" data-role="to-label" style=""></div>
                <button class="action tocart primary">
                    <span>
                        <span>Reset</span>
                    </span>
                </button>
                <button data-bind="click: _getNearestStores" class="action tocart primary" type="submit" title="Search for Store">
                    <span>Search</span>
                </button>
            </div>
</div>
<div class="row">
    <div class="storefinder-list-wrapper col-tn-12  col-xs-6  col-sm-6 col-md-5  col-lg-4">
        <div class="store-finder-header" style="border-bottom:0px;">
            <p> <i class="fa fa-bars fa-15x" aria-hidden="true"></i>
                <?php echo  __('Store List')?>
            </p>
        </div>
        <div  id="stores"  style="overflow:scroll;height:550px;overflow-x: hidden;" class="storefinder-list-inner-wrapper" data-bind="scope:'stores'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>

    <div class="col-tn-12 col-xs-6 col-sm-6 col-md-7 col-lg-8">
        <div  id="map"  data-role="storefinder-googlemap" style="height:589px;">

        </div>
    </div>
</div>

    <script>
        window.configs = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
<script type="text/x-magento-init">
                {
                    "*": {
                        "Magento_Ui/js/core/app": {
                           "components": {
                                "search": {
                                    "component": "Peasoup_Storefinder/js/search",
                                    "template" : "Peasoup_Storefinder/search-new"
                                },
                                "stores": {
                                    "component": "Peasoup_Storefinder/js/storesList",
                                    "template" : "Peasoup_Storefinder/storeslist",
                                    "baseUrl":"<?php echo $block->getMediaPath();?>"
                                }
                            }
                        }
                    },
                    "[data-role=storefinder-googlemap]" : {
                                               "googleMap" :{}
                                               },
                    "[data-role=storefinder-distance-slider]" : {
                                               "distanceSlider" :{}
                    }
                }
</script>
